name: online_shopping
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  page_transition: ^2.0.9
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.1.2
  get_it: ^7.6.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  animate_do: ^3.0.2
  bloc: ^8.1.2
  stream_transform: ^2.1.0
  google_sign_in: ^6.1.4
  fluttertoast: ^8.2.2
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  animated_text_kit: ^4.2.2
  intl: ^0.18.1
  lottie: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - assets/json/
   - assets/fonts/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Metropolis-Bold.otf
          weight: 700
        - asset: assets/fonts/Metropolis-Black.otf
          weight: 600
        - asset: assets/fonts/Metropolis-Medium.otf
          weight: 500
        - asset: assets/fonts/Metropolis-Regular.otf
          weight: 400
        - asset: assets/fonts/Metropolis-Light.otf
          weight: 300
