// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLFvBWHxr6lCAwLWoRETs0OlWFjXU0JFI',
    appId: '1:422558597284:web:e992ee385cf8632cc7e631',
    messagingSenderId: '422558597284',
    projectId: 'online-shopping-2468b',
    authDomain: 'online-shopping-2468b.firebaseapp.com',
    storageBucket: 'online-shopping-2468b.appspot.com',
    measurementId: 'G-EMMXB22XZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Zy27kZR8-my0-0c6wbqd7wJeMqqwahk',
    appId: '1:422558597284:android:cad38a6f121c983bc7e631',
    messagingSenderId: '422558597284',
    projectId: 'online-shopping-2468b',
    storageBucket: 'online-shopping-2468b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMriZehY8zw6rZX1-Zm7mLQTrNoy_3SxM',
    appId: '1:422558597284:ios:01b9189accc10292c7e631',
    messagingSenderId: '422558597284',
    projectId: 'online-shopping-2468b',
    storageBucket: 'online-shopping-2468b.appspot.com',
    iosClientId: '422558597284-u5bhaohjo2grt2tucc7kvtdoq9gjjqmb.apps.googleusercontent.com',
    iosBundleId: 'com.onlineshopping.onlineShopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMriZehY8zw6rZX1-Zm7mLQTrNoy_3SxM',
    appId: '1:422558597284:ios:49f50e658d8bbc61c7e631',
    messagingSenderId: '422558597284',
    projectId: 'online-shopping-2468b',
    storageBucket: 'online-shopping-2468b.appspot.com',
    iosClientId: '422558597284-ah0k63uuhrgd0f9vh6u7mkrgv18rrndm.apps.googleusercontent.com',
    iosBundleId: 'com.onlineshopping.onlineShopping.RunnerTests',
  );
}
